### ISSUE TITLE
Convert to UIKit / SwiftUI

### ISSUE THREAD

**Issue by prestonattebery** [BenEmdon/PixelArtMaker#1]
What's the best way to get this in a Swift project and out of Playgrounds?

**Comment by BenEmdon** [comment]
Hey @prestonattebery 👋 

The goal of this project was to build a Swift project within the Swift Playground environment. Certain design decisions limit this project from working outside of Swift Playgrounds:
* Relying on Playground APIs
* Using static sizes, and not resizing based on the screen size (no auto layout)

If you wanted to use this piece of work outside of a Swift Playground I anticipate you would need to rewrite the project to account for these constraints. That being said, this project provides a good resource for those looking to reproduce such a project. 😄
